AWSTemplateFormatVersion: '2010-09-09'
Description: S3 bucket with versioning enabled to test drift detection.

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: drift-demo-s3-bucket-demo-drift
      VersioningConfiguration:
        Status: disabled