AWSTemplateFormatVersion: '2010-09-09'
Description: Create an EC2 instance and an S3 bucket.

Resources:
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: ami-0c02fb55956c7d316 # Amazon Linux 2 AMI in us-east-1 
      KeyName: my-key-pair # Replace with your key pair name
      SecurityGroupIds:
        - !Ref MySecurityGroup
      Tags:
        - Key: Name
          Value: MyCloudFormationEC2

  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow SSH and HTTP access
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0 # Allow SSH from anywhere
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0 # Allow HTTP from anywhere

  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-cloudformation-s3-bucket-ravishan
      AccessControl: Private
      Tags:
        - Key: Name
          Value: MyCloudFormationS3Bucket

Outputs:
  InstanceId:
    Description: EC2 instance ID
    Value: !Ref MyEC2Instance

  BucketName:
    Description: S3 bucket name
    Value: !Ref MyS3Bucket